# Pivot Table

<p>The pivot table takes simple column-wise data as input, and groups the entries into a two-dimensional table that provides a multidimensional summarization of the data.</p>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
df = sns.load_dataset('tips')
df.sample(5)

     total_bill   tip     sex smoker  day    time  size
12        15.42  1.57    Male     No  Sun  Dinner     2
181       23.33  5.65    Male    Yes  Sun  Dinner     2
207       38.73  3.00    Male    Yes  Sat  Dinner     4
219       30.14  3.09  Female    Yes  Sat  Dinner     4
217       11.59  1.50    Male    Yes  Sat  Dinner     2

In [5]:
df.groupby('sex')[['total_bill']].mean()

C:\Users\HP\AppData\Local\Temp\ipykernel_6092\2388094044.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')[['total_bill']].mean()

        total_bill
sex
Male     20.744076
Female   18.056897

In [8]:
df.groupby(['sex', 'smoker'])[['total_bill']].mean().unstack()

C:\Users\HP\AppData\Local\Temp\ipykernel_6092\2059578668.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex', 'smoker'])[['total_bill']].mean().unstack()

       total_bill
smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [11]:
df.pivot_table(index = 'sex', columns = 'smoker', values = 'total_bill')

C:\Users\HP\AppData\Local\Temp\ipykernel_6092\2453703127.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = 'sex', columns = 'smoker', values = 'total_bill')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185