# GroupBy on Multiple Columns

In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('imdb-top-1000.csv')
movies.head(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0

In [3]:
movie = movies.groupby(['Director', 'Star1'])
movie

In [4]:
# size()
movie.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [5]:
# get_group()
movie.get_group(('Aamir Khan', 'Amole Gupte'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [16]:
# Find the most earning actor-director combo
actor_director_combo = movie['Gross'].sum()
actor_director_combo

Director             Star1
Aamir Khan           Amole Gupte         1223869.0
Aaron Sorkin         Eddie Redmayne    853090410.0
Abdellatif Kechiche  Léa Seydoux         2199675.0
Abhishek Chaubey     Shahid Kapoor     218428303.0
Abhishek Kapoor      Amit Sadh           1122527.0
                                          ...
Zaza Urushadze       Lembit Ulfsak        144501.0
Zoya Akhtar          Hrithik Roshan      3108485.0
                     Vijay Varma         5566534.0
Çagan Irmak          Çetin Tekindor    461855363.0
Ömer Faruk Sorak     Cem Yilmaz        196206077.0
Name: Gross, Length: 898, dtype: float64

In [17]:
actor_director_combo.sort_values(ascending = False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [13]:
# Find the best(in-terms of metascore(avg)) actor-genre combo
actor_genre_combo = movies.groupby(['Star1', 'Genre'])['Metascore'].mean()
actor_genre_combo

Star1                 Genre
Aamir Khan            Action        NaN
                      Adventure    84.0
                      Comedy       67.0
Aaron Taylor-Johnson  Action       66.0
Abhay Deol            Drama         NaN
                                   ...
Zbigniew Zamachowski  Comedy       88.0
Zooey Deschanel       Comedy       76.0
Çetin Tekindor        Drama         NaN
Éric Toledano         Biography    57.0
Ömer Faruk Sorak      Comedy        NaN
Name: Metascore, Length: 829, dtype: float64

In [14]:
# this is multi index series
actor_genre_combo.reset_index() # to convert it DF

                    Star1      Genre  Metascore
0              Aamir Khan     Action        NaN
1              Aamir Khan  Adventure       84.0
2              Aamir Khan     Comedy       67.0
3    Aaron Taylor-Johnson     Action       66.0
4              Abhay Deol      Drama        NaN
..                    ...        ...        ...
824  Zbigniew Zamachowski     Comedy       88.0
825       Zooey Deschanel     Comedy       76.0
826        Çetin Tekindor      Drama        NaN
827         Éric Toledano  Biography       57.0
828      Ömer Faruk Sorak     Comedy        NaN

[829 rows x 3 columns]

In [19]:
a_g_combo = actor_genre_combo.reset_index().sort_values('Metascore', ascending = False)
a_g_combo

                Star1      Genre  Metascore
606     Peter O'Toole  Adventure      100.0
590      Orson Welles      Drama      100.0
77        Bertil Guve      Drama      100.0
230    Ellar Coltrane      Drama      100.0
329   Humphrey Bogart      Drama      100.0
..                ...        ...        ...
807    William Holden      Drama        NaN
812           Won Bin     Action        NaN
815              Yash     Action        NaN
826    Çetin Tekindor      Drama        NaN
828  Ömer Faruk Sorak     Comedy        NaN

[829 rows x 3 columns]

In [21]:
a_g_combo.head(1)

             Star1      Genre  Metascore
606  Peter O'Toole  Adventure      100.0

In [23]:
# agg on multiple groupby
movie[movies.select_dtypes(include = 'number').columns].agg(['min', 'max', 'mean'])

                                   Runtime             IMDB_Rating            \
                                       min  max   mean         min  max mean
Director            Star1
Aamir Khan          Amole Gupte        165  165  165.0         8.4  8.4  8.4
Aaron Sorkin        Eddie Redmayne     129  129  129.0         7.8  7.8  7.8
Abdellatif Kechiche Léa Seydoux        180  180  180.0         7.7  7.7  7.7
Abhishek Chaubey    Shahid Kapoor      148  148  148.0         7.8  7.8  7.8
Abhishek Kapoor     Amit Sadh          130  130  130.0         7.7  7.7  7.7
...                                    ...  ...    ...         ...  ...  ...
Zaza Urushadze      Lembit Ulfsak       87   87   87.0         8.2  8.2  8.2
Zoya Akhtar         Hrithik Roshan     155  155  155.0         8.1  8.1  8.1
                    Vijay Varma        154  154  154.0         8.0  8.0  8.0
Çagan Irmak         Çetin Tekindor     112  112  112.0         8.3  8.3  8.3
Ömer Faruk Sorak    Cem Yilmaz         127  127  127.0         8.0  8.0  8.0

                                   No_of_Votes                          Gross  \
                                           min     max      mean          min
Director            Star1
Aamir Khan          Amole Gupte         168895  168895  168895.0    1223869.0
Aaron Sorkin        Eddie Redmayne       89896   89896   89896.0  853090410.0
Abdellatif Kechiche Léa Seydoux         138741  138741  138741.0    2199675.0
Abhishek Chaubey    Shahid Kapoor        27175   27175   27175.0  218428303.0
Abhishek Kapoor     Amit Sadh            32628   32628   32628.0    1122527.0
...                                        ...     ...       ...          ...
Zaza Urushadze      Lembit Ulfsak        40382   40382   40382.0     144501.0
Zoya Akhtar         Hrithik Roshan       67927   67927   67927.0    3108485.0
                    Vijay Varma          31886   31886   31886.0    5566534.0
Çagan Irmak         Çetin Tekindor       78925   78925   78925.0  461855363.0
Ömer Faruk Sorak    Cem Yilmaz           56960   56960   56960.0  196206077.0

                                                             Metascore        \
                                            max         mean       min   max
Director            Star1
Aamir Khan          Amole Gupte       1223869.0    1223869.0       NaN   NaN
Aaron Sorkin        Eddie Redmayne  853090410.0  853090410.0      77.0  77.0
Abdellatif Kechiche Léa Seydoux       2199675.0    2199675.0      89.0  89.0
Abhishek Chaubey    Shahid Kapoor   218428303.0  218428303.0       NaN   NaN
Abhishek Kapoor     Amit Sadh         1122527.0    1122527.0      40.0  40.0
...                                         ...          ...       ...   ...
Zaza Urushadze      Lembit Ulfsak      144501.0     144501.0      73.0  73.0
Zoya Akhtar         Hrithik Roshan    3108485.0    3108485.0       NaN   NaN
                    Vijay Varma       5566534.0    5566534.0      65.0  65.0
Çagan Irmak         Çetin Tekindor  461855363.0  461855363.0       NaN   NaN
Ömer Faruk Sorak    Cem Yilmaz      196206077.0  196206077.0       NaN   NaN


                                    mean
Director            Star1
Aamir Khan          Amole Gupte      NaN
Aaron Sorkin        Eddie Redmayne  77.0
Abdellatif Kechiche Léa Seydoux     89.0
Abhishek Chaubey    Shahid Kapoor    NaN
Abhishek Kapoor     Amit Sadh       40.0
...                                  ...
Zaza Urushadze      Lembit Ulfsak   73.0
Zoya Akhtar         Hrithik Roshan   NaN
                    Vijay Varma     65.0
Çagan Irmak         Çetin Tekindor   NaN
Ömer Faruk Sorak    Cem Yilmaz       NaN

[898 rows x 15 columns]